### ISSUE TITLE
Fix a bug in FileBuilder::fromDateFormat (or time_from_string)

### ISSUE THREAD

**Issue by kzhereb** [SoftwareEngineeringStudyProjects/KnowYourKnowledge#38]
Looks like it produces std::time_t instance with wrong hour:
time_helper_test.cpp:19: ERROR: CHECK( time_from_string(current_str) == current ) is NOT correct!
  values: CHECK( 1664539645 == 1664536045 )
(difference is exactly 3600)
time_helper_test.cpp:21: ERROR: CHECK( time_to_string(time_from_string(current_str)) == current_str ) is NOT correct!
  values: CHECK( 2022.09.30 15:07:25 == 2022.09.30 14:07:25 )

**Comment by MouseCreator** [comment]
Very unexpected bug, since tm_hour is not changed in the code. I suggest that it's a tm_isdst bug, because Daylight Saving Time is actually 1 hour difference in time. I'd add tm.tm_isdst = -1 in the method, but don't want to commit w/o testing it yet, so I'll just leave this comment for now :)

**Comment by kzhereb** [comment]
Looks like setting tm.tm_isdst = -1 fixes this bug, which corresponds to documentation https://en.cppreference.com/w/cpp/chrono/c/tm 
"The value is positive if DST is in effect, zero if not and negative if no information is available"
Probably fixed in d299d80edefd83b640d25f7615d72b74e7e75205
